### ISSUE TITLE
[Bug] Must run inside project generated with react-native-cli

### ISSUE THREAD

**Issue by luchillo17** [kristianmandrup/slush-react-native-ts-generator#1]
## Environment
- React native cli: 2.0.1
- Slush: 1.1.1
- Slush react native ts generator: 0.1.1

## Output
![image](https://user-images.githubusercontent.com/9698639/27013249-ed77b422-4ea5-11e7-8a85-885a17b4ba01.png)

**Comment by kristianmandrup** [comment]
Can be fixed here:

https://github.com/kristianmandrup/slush-react-native-ts-generator/blob/master/default/tasks.js#L42

**Comment by kristianmandrup** [comment]
Pushed new version with fix. Give it a try. Thanks

**Comment by luchillo17** [comment]
New output, look at that comma typo after web, that dot should be a comma:
![image](https://user-images.githubusercontent.com/9698639/27014623-54eb7ac8-4ec2-11e7-8e8b-51f4fbd9da42.png)

**Comment by kristianmandrup** [comment]
Thanks. Pushed fix to comma. Haven't used React or RN in long time... You are most welcome to continue/improve this generator as you see fit to suit your needs and prefs.
